
TIME_INTERVAL_FOR_BILL_PAYMENT = 5*60
LIMIT_ON_NUMBER_OF_BILLS = 5
LIMIT_ON_AMOUNT_OF_BILLS = 20000
SECONDS_TO_WAIT_FOR_ADMIN_ALERT = 15*60

LOG_EVENTS_PATH = './static/logs.txt'

class ConnectorConfig():
	mongoIp = 'localhost'
	port = 27017